### PR TITLE
Issues

### PR DESCRIPTION
**Pull request by Doroshenko-T**
Issue #1

20231002  Pre-release

This error occurs some time after installing version 20231002:

20231002_After_Install

### CODE REVIEW

**Comment by Doroshenko-T** [comment]
Issue #2

20231002 Pre-release

This errors occurs every time after the launch of version 20231002:
20231002_Each_Start

**Comment by Doroshenko-T** [comment]
Issue #3 
A fatal bug was detected in displaying the Cyrillic in the File System.
When accessing Manjaro externally using Midnight Commander over the Shell protocol, directory and file names are garbled and cannot be accessed.
This bug does not allow me to copy files to or from Manjaro from another computer.

Distorted_Cyrillic:

7d96e7d4c2692d1ad1c301d204a276c5d2dac9ea


Real_Cyrillic:

69fdb5ad43262ad1e49dbc572ae5ce1f6ae3ce29

**Comment by Doroshenko-T** [comment]
I kindly ask you to implement Power-On  and Power-Off the Gt-King  using  its native remote control.
Because doing this with a plug by electrical socket is very inconvenient.

plug and socket

**Comment by spikerguy** [comment]
> I kindly ask you to implement Power-On and Power-Off the Gt-King using its native remote control. Because doing this with a plug by electrical socket is very inconvenient.
> 
> plug and socket

This wont be possible using android bootloader. 

You will have to use a bootloader which supports thats on linux.

**Comment by Doroshenko-T** [comment]
>  You will have to use a bootloader which supports thats on linux.

Okay, and how can this be done? Talk me, please

**Pull request closed without merging**
